# Generated by Django 4.0.4 on 2022-04-28 16:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path_geom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
                ('length', models.CharField(max_length=50)),
                ('type', models.TextField()),
                ('name', models.CharField(max_length=30, null=True)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('age', models.TextField(blank=True)),
                ('picture', models.TextField(blank=True)),
            ],
        ),
    ]
