# Generated by Django 4.0 on 2022-03-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path_geom',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=200)),
                ('geom', models.TextField()),
                ('length', models.CharField(max_length=50)),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('age', models.TextField(blank=True)),
                ('picture', models.TextField(blank=True)),
            ],
        ),
    ]
