# Generated by Django 3.2.7 on 2022-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path_geom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', models.TextField()),
                ('length', models.CharField(max_length=50)),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.TextField()),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='StrollingPath',
        ),
    ]
